name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Smoke Test Application
        run: |
          java -jar target/rest-0.0.1-SNAPSHOT.jar &
          sleep 30
          curl -f http://localhost:8080/ || exit 1
          echo "Smoke test passed!"
