filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/app.log
    json.keys_under_root: true
    json.add_error_key: true

setup.template.enabled: false
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "crud-logs-%{+yyyy.MM.dd}"

setup.template.name: "crud-logs"
setup.template.pattern: "crud-logs-*"